apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
  name: workshop
spec:
  selector:
    app: workshop
  ports:
    - nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workshop
  name: workshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workshop
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      - image: hello-workshop:v1
        name: hello-workshop
        resources: {}
